#! /bin/bash

TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
instance_id=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -sS http://169.254.169.254/latest/meta-data/instance-id)
profile_name="$(jq < cfn-output.json -r '.ProfileName')"

if aws ec2 associate-iam-instance-profile --iam-instance-profile "Name=$profile_name" --instance-id $instance_id; then
  echo "Profile associated successfully."
else
  echo "WARNING: Encountered error associating instance profile with Cloud9 environment"
fi
