#!/bin/bash



# Define local variables for ALB full name
PRIMARY_ALB_FULL_NAME=$(jq < cfn-output.json -r '.LoadBalancerFullName')
SECONDARY_ALB_FULL_NAME=$(jq < cfn-output-secondary.json -r '.LoadBalancerFullName')

# Define local variables for CORE ECS service
PRIMARY_CORE_ECS_SERVICE=$(jq < cfn-output.json -r '.CoreEcsServiceName')
SECONDARY_CORE_ECS_SERVICE=$(jq < cfn-output-secondary.json -r '.CoreEcsServiceName')

# Define local variables for LIKE ECS service
PRIMARY_LIKE_ECS_SERVICE=$(jq < cfn-output.json -r '.LikeEcsServiceName')
SECONDARY_LIKE_ECS_SERVICE=$(jq < cfn-output-secondary.json -r '.LikeEcsServiceName')

# Define local variables for ECS cluster
PRIMARY_ECS_CLUSTER=$(jq < cfn-output.json -r '.EcsClusterName')
SECONDARY_ECS_CLUSTER=$(jq < cfn-output-secondary.json -r '.EcsClusterName')

# Define local variables for regions
PRIMARY_REGION=$(jq < cfn-output.json -r '.CurrentRegion')
SECONDARY_REGION=$(jq < cfn-output-secondary.json -r '.SecondaryRegion')

# Define local variable for DynamoDB Table
DDBTABLE=$(jq < cfn-output.json -r '.DynamoTable')

cp app/hints/cwdashboard_with_replacements.yml ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_PRIMARY_ALB_FULL_NAME;'"$PRIMARY_ALB_FULL_NAME"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_SECONDARY_ALB_FULL_NAME;'"$SECONDARY_ALB_FULL_NAME"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_PRIMARY_CORE_ECS_SERVICE;'"$PRIMARY_CORE_ECS_SERVICE"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_SECONDARY_CORE_ECS_SERVICE;'"$SECONDARY_CORE_ECS_SERVICE"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_PRIMARY_LIKE_ECS_SERVICE;'"$PRIMARY_LIKE_ECS_SERVICE"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_SECONDARY_LIKE_ECS_SERVICE;'"$SECONDARY_LIKE_ECS_SERVICE"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_PRIMARY_ECS_CLUSTER;'"$PRIMARY_ECS_CLUSTER"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_SECONDARY_ECS_CLUSTER;'"$SECONDARY_ECS_CLUSTER"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_PRIMARY_REGION;'"$PRIMARY_REGION"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_SECONDARY_REGION;'"$SECONDARY_REGION"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_DDBTABLE;'"$DDBTABLE"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml

# We have to do a second pass of the file...
sed -i -e 's;REPLACEME_PRIMARY_ALB_FULL_NAME;'"$PRIMARY_ALB_FULL_NAME"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_SECONDARY_ALB_FULL_NAME;'"$SECONDARY_ALB_FULL_NAME"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_PRIMARY_CORE_ECS_SERVICE;'"$PRIMARY_CORE_ECS_SERVICE"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_SECONDARY_CORE_ECS_SERVICE;'"$SECONDARY_CORE_ECS_SERVICE"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_PRIMARY_LIKE_ECS_SERVICE;'"$PRIMARY_LIKE_ECS_SERVICE"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_SECONDARY_LIKE_ECS_SERVICE;'"$SECONDARY_LIKE_ECS_SERVICE"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_PRIMARY_ECS_CLUSTER;'"$PRIMARY_ECS_CLUSTER"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_SECONDARY_ECS_CLUSTER;'"$SECONDARY_ECS_CLUSTER"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_PRIMARY_REGION;'"$PRIMARY_REGION"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_SECONDARY_REGION;'"$SECONDARY_REGION"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
sed -i -e 's;REPLACEME_DDBTABLE;'"$DDBTABLE"';' ~/environment/aws-multi-region-bc-dr-workshop/cwdashboard_multiregion.yml
