#!/bin/bash

LIKE_GIT_REPO_NAME=$(jq < cfn-output.json -r '.MythicalLikeGitRepositoryName')
CORE_GIT_REPO_NAME=$(jq < cfn-output.json -r '.MythicalCoreGitRepositoryName')

SECONDARY_LIKE_ECR_REPO_URI=$(jq < cfn-output-secondary.json -r '.SecondaryLikeServiceEcrRepo')
SECONDARY_CORE_ECR_REPO_URI=$(jq < cfn-output-secondary.json -r '.SecondaryCoreServiceEcrRepo')
SECONDARY_REGION=$(jq < cfn-output-secondary.json -r '.SecondaryRegion')

LIKE_ECR_REPO_URI=$(jq < cfn-output.json -r '.LikeServiceEcrRepo')
CORE_ECR_REPO_URI=$(jq < cfn-output.json -r '.CoreServiceEcrRepo')

cp app/hints/like-buildspec_prod.yml ~/environment/$LIKE_GIT_REPO_NAME/buildspec_prod.yml
sed -i -e 's;REPLACEME_SECONDARY_REPO_URI;'"$SECONDARY_LIKE_ECR_REPO_URI"';' ~/environment/$LIKE_GIT_REPO_NAME/buildspec_prod.yml
sed -i -e 's;REPLACEME_PRIMARY_REPO_URI;'"$LIKE_ECR_REPO_URI"';' ~/environment/$LIKE_GIT_REPO_NAME/buildspec_prod.yml
sed -i -e 's;REPLACEME_SECONDARY_REGION;'"$SECONDARY_REGION"';' ~/environment/$LIKE_GIT_REPO_NAME/buildspec_prod.yml

cp app/hints/core-buildspec_prod.yml ~/environment/$CORE_GIT_REPO_NAME/buildspec_prod.yml
sed -i -e 's;REPLACEME_SECONDARY_REPO_URI;'"$SECONDARY_CORE_ECR_REPO_URI"';' ~/environment/$CORE_GIT_REPO_NAME/buildspec_prod.yml
sed -i -e 's;REPLACEME_PRIMARY_REPO_URI;'"$CORE_ECR_REPO_URI"';' ~/environment/$CORE_GIT_REPO_NAME/buildspec_prod.yml
sed -i -e 's;REPLACEME_SECONDARY_REGION;'"$SECONDARY_REGION"';' ~/environment/$CORE_GIT_REPO_NAME/buildspec_prod.yml

cd ~/environment/$LIKE_GIT_REPO_NAME/
git add -A
git commit -m "Updating Like Service to upload image to secondary region"
git push origin master

cd ~/environment/$CORE_GIT_REPO_NAME/
git add -A
git commit -m "Updating Core Service to upload image to secondary region"
git push origin master

# Mod hint file
# Modding hints
#
#
# sed -i -e 's;REPLACEME_PRIMARY_REPO_URI;'"$CORE_ECR_REPO_URI"';' app/hints/mysfits-service-buildspec_prod.yml
#
# sed -i -e 's;REPLACEME_SECONDARY_REPO_URI;'"$SECONDARY_LIKE_ECR_REPO_URI"';' ~/environment/$LIKE_REPO_NAME/buildspec_prod.yml
# sed -i -e 's;REPLACEME_SECONDARY_REPO_URI;'"$SECONDARY_CORE_ECR_REPO_URI"';' app/hints/mysfits-service-buildspec_prod.yml
